### ISSUE TITLE
Add support for "default" taxonomy term(s)

### ISSUE THREAD

**Issue by JacobDB** [johnbillion/extended-cpts#122] opened 2019-07-16 16:15 UTC
Similar to how posts have a default "Uncategorized" category, it'd be awesome if we could set a default term for our custom taxonomies, which can't be deleted, and when unselected gets re-added.

**Comment by johnbillion** [comment] 2019-07-16 17:28
Yeah I would definitely like to do this at some point.

Duplicate of #71.

**Closed by johnbillion** 2019-07-16 17:28 UTC

**Comment by JacobDB** [comment] 2019-07-16 17:46
Ah, thanks, I searched but didn't find that issue.
