### ISSUE TITLE
2.5.1 breaks featured images on posts in 4.3

### ISSUE THREAD

**Issue by danielhomer** [johnbillion/extended-cpts#30] opened 2015-11-03 09:53 UTC
In 2.5, the plugin passed featured image labels which fixed the featured images in posts on 4.3, however, this fix was removed in 2.5.1 https://github.com/johnbillion/extended-cpts/commit/c95ef1f6bb311f3d3053ecff0da4cafcaaf3eb2b, so the box is has gone walkabout again.

**Comment by johnbillion** [comment] 2015-11-03 11:48
Hey Daniel,

The featured image labels aren't required as WP will populate them with the default strings if they're not provided. Are you doing anything different with post type labels? Can you let me know how you're registering your post type?

**Comment by danielhomer** [comment] 2015-11-03 13:23
Hey, I've done some more digging and found that the bug is down to us using extended-cpts to extend the core `post` post type. 

E.g:

	// Override post post type, to add some columns
	$post_args = array(
		'labels' => array(
			'name_admin_bar' => _x( 'Post', 'add new on admin bar' ),
		),
		'admin_cols' => array(
			'title',
			'author',
			'publication' => array(
				'title'      => 'Publication',
				'connection' => 'publication_to_post',
				'link'       => true,
			),
			'categories',
			'tags',
			'comments',
			'date'
		),
	);
	$post = register_extended_post_type( 'post', $post_args );

As the `extend()` method in extended-cpts only uses the labels set in `$args` when modifying the global post type object, the featured image labels are missed. 

I've created a PR (https://github.com/johnbillion/extended-cpts/pull/31) which fixes this issue, but it might be worth doing something earlier on in the constructor.

**Comment by johnbillion** [comment] 2015-11-03 13:24
Ah, thanks! :+1:  This is probably the same issue as #27 then. I'll take a look at the PR a little later.

**Comment by johnbillion** [comment] 2015-11-03 13:25
Related: #16

**Comment by johnbillion** [comment] 2015-11-12 20:35
Closing as a dupe of #27.

**Closed by johnbillion** 2015-11-12 20:35 UTC
